"""empty message

Revision ID: 2f640b8fb348
Revises: 0736a0b02d39
Create Date: 2022-05-24 22:00:42.163294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f640b8fb348'
down_revision = '0736a0b02d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'author_id')
    # ### end Alembic commands ###
